src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    /**
     * @var Collection<int, Partido>
     */
    #[ORM\OneToMany(targetEntity: Partido::class, mappedBy: 'idUsuario')]
    private Collection $partidos;

    #[ORM\Column(length: 255)]
    private ?string $username = null;

    /**
     * @var Collection<int, PeticionRol>
     */
    #[ORM\OneToMany(targetEntity: PeticionRol::class, mappedBy: 'usuario')]
    private Collection $peticionRoles;

    /**
     * @var Collection<int, Competicion>
     */
    #[ORM\OneToMany(targetEntity: Competicion::class, mappedBy: 'admin')]
    private Collection $competiciones;

    /**
     * @var Collection<int, Competicion>
     */
    #[ORM\ManyToMany(targetEntity: Competicion::class, inversedBy: 'estadistas')]
    private Collection $competicionesEstadista;

    public function __construct()
    {
        $this->partidos = new ArrayCollection();
        $this->peticionRoles = new ArrayCollection();
        $this->competiciones = new ArrayCollection();
        $this->competicionesEstadista = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Partido>
     */
    public function getPartidos(): Collection
    {
        return $this->partidos;
    }

    public function addPartido(Partido $partido): static
    {
        if (!$this->partidos->contains($partido)) {
            $this->partidos->add($partido);
            $partido->setIdUsuario($this);
        }

        return $this;
    }

    public function removePartido(Partido $partido): static
    {
        if ($this->partidos->removeElement($partido)) {
            // set the owning side to null (unless already changed)
            if ($partido->getIdUsuario() === $this) {
                $partido->setIdUsuario(null);
            }
        }

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @return Collection<int, PeticionRol>
     */
    public function getPeticionRol(): Collection
    {
        return $this->peticionRoles;
    }

    public function addPeticionRol(PeticionRol $peticionRole): static
    {
        if (!$this->peticionRoles->contains($peticionRole)) {
            $this->peticionRoles->add($peticionRole);
            $peticionRole->setUsuario($this);
        }

        return $this;
    }

    public function removePeticionRole(PeticionRol $peticionRole): static
    {
        if ($this->peticionRoles->removeElement($peticionRole)) {
            // set the owning side to null (unless already changed)
            if ($peticionRole->getUsuario() === $this) {
                $peticionRole->setUsuario(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Competicion>
     */
    public function getCompeticiones(): Collection
    {
        return $this->competiciones;
    }

    public function addCompeticione(Competicion $competicione): static
    {
        if (!$this->competiciones->contains($competicione)) {
            $this->competiciones->add($competicione);
            $competicione->setAdmin($this);
        }

        return $this;
    }

    public function removeCompeticione(Competicion $competicione): static
    {
        if ($this->competiciones->removeElement($competicione)) {
            // set the owning side to null (unless already changed)
            if ($competicione->getAdmin() === $this) {
                $competicione->setAdmin(null);
            }
        }

        return $this;
    }

    public function getCompeticionesEstadista(): Collection
    {
        return $this->competicionesEstadista;
    }

    public function addCompeticioneEstadista(Competicion $competicion): static
    {
        if (!$this->competicionesEstadista->contains($competicion)) {
            $this->competicionesEstadista->add($competicion);
            $competicion->addEstadista($this);
        }

        return $this;
    }

    public function removeCompeticioneEstadista(Competicion $competicion): static
    {
        if ($this->competicionesEstadista->removeElement($competicion)) {
            $competicion->removeEstadista($this);
        }

        return $this;
    }

}

src/Form/RegistrationFormType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\IsTrue;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class RegistrationFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username', TextType::class, [
                'label' => 'Nombre de usuario',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Por favor ingresa un nombre de usuario',
                    ]),
                    new Length([
                        'min' => 3,
                        'minMessage' => 'Tu nombre de usuario debe tener al menos {{ limit }} caracteres',
                        'max' => 180,
                    ]),
                ],
            ])
            ->add('email')
            ->add('plainPassword', PasswordType::class, [
                // instead of being set onto the object directly,
                // this is read and encoded in the controller
                'mapped' => false,
                'attr' => ['autocomplete' => 'new-password'],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a password',
                    ]),
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Your password should be at least {{ limit }} characters',
                        // max length allowed by Symfony for security reasons
                        'max' => 4096,
                    ]),
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

templates/forms/competicionEdit.html.twig
<div class="modal fade" id="modalEditarCompeticion" tabindex="-1" aria-labelledby="modalEditarCompeticionLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="titulomodalEditarCompeticion">Editar Competicion</h5>
                <button type="button" class="btn-close cerrar-modal-competicion" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>

            <div class="modal-body">
                <div class="alert alert-success d-none" id="alerta-modal-editar" role="alert">
                    Competicion actualizada correctamente.
                </div>
                <form id="formEditarCompeticion" method="post">
                    <input type="hidden" id="competicion-id" name="competicion-id">

                    <div class="mb-3">
                        <label for="nombre-competicion" class="form-label">Nombre de la Competición</label>
                        <input type="text" name="nombre-competicion" class="form-control" id="nombre-competicion" required>
                    </div>

                    <button type="submit" class="btn btn-success">Guardar</button>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary cerrar-modal-competicion" data-bs-dismiss="modal">Cerrar</button>
            </div>

        </div>
    </div>
</div>

<script>
    $('#formEditarCompeticion').submit(function (e) {
        e.preventDefault();

        const id = $('#competicion-id').val();
        const datos = {
            nombreCompeticion: $('#nombre-competicion').val(),
        };

        $.ajax({
            url: `/admin/competicion/${id}/edit`,
            type: 'PUT',
            data: datos,
            success: function () {
                const alerta = $('#alerta-modal-editar');
                alerta.removeClass('d-none');
            },
            error: function () {
                alert('Error al editar la Competicion.');
            }
        });
    });

    $('.cerrar-modal-competicion').on('click', function () {
        $('#btn-competiciones').trigger('click');
        $('#alerta-modal-editar').addClass('d-none');
    });

</script>

templates/forms/competicionNueva.html.twig
<div class="modal fade" id="modalCrearCompeticion" tabindex="-1" aria-labelledby="modalCrearCompeticion" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="titulomodalCrearCompeticion">Crear Competicion</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>

            <div class="modal-body">
                <form id="formCrearCompeticion" action="{{ path('crear_competicion') }}" method="post">

                    <div class="mb-3">
                        <label for="nombreCompeticion" class="form-label">Nombre de la Competicion</label>
                        <input type="text" name="nombreCompeticion" class="form-control" id="nombreCompeticion" required>
                    </div>

                    <button type="submit" class="btn btn-success">Guardar</button>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>

        </div>
    </div>
</div>

templates/forms/datosUsuario.html.twig
<h1>Editar tu información</h1>

<form method="POST">
    <div class="form-group">
        <label for="username">Nombre de Usuario</label>
        <input type="text" id="username" name="username" class="form-control" value="{{ app.user.username }}" disabled>
    </div>

    <div class="form-group">
        <label for="email">Correo Electrónico</label>
        <input type="email" id="email" name="email" class="form-control" value="{{ app.user.email }}" disabled>
    </div>

    <div class="form-group">
        <label for="password">Contraseña</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Deja vacío para no cambiar" disabled>
    </div>

    <div class="form-group">
        <label for="roles">Roles</label>
        <input type="text" id="roles" class="form-control" value="{{ app.user.roles|join(', ') }}" disabled>
    </div>

</form>

{% if app.user.peticionRol|filter(p => p.status.value == 'PENDING')|length == 0 %}
    <form method="post" action="/usuario/{{ app.user.id }}/peticion-rol">
        <div class="form-group">
            <label for="competicion">Selecciona una competición:</label>
            <select name="competicion_id" id="competicion" class="form-control">
                {% set hayDisponibles = false %}
                {% for competicion in competiciones %}
                    {% set yaAsignado = app.user.competicionesEstadista is defined and competicion in app.user.competicionesEstadista %}
                    {% set esAdmin = competicion.admin.id == app.user.id %}
                    {% if not yaAsignado and not esAdmin %}
                        {% set hayDisponibles = true %}
                        <option value="{{ competicion.id }}">{{ competicion.nombre }} - {{ competicion.admin.username }}</option>
                    {% endif %}

                {% endfor %}
                {% if not hayDisponibles %}
                    <option disabled selected>No hay competiciones disponibles</option>
                {% endif %}
            </select>
        </div>
        {% if hayDisponibles %}
        <button type="submit" class="btn btn-secondary mt-3">Solicitar rol de Estadista</button>
        {% endif %}
    </form>
{% endif %}

{% set peticion = app.user.peticionRol|last %}
{% if peticion %}
    <div class="mt-4">
        {% if peticion.status.value == 'PENDING' %}
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                Tienes una solicitud pendiente ({{ peticion.competicion.nombre }}).
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% elseif peticion.status.value == 'APPROVED' %}
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                Tu solicitud sobre "{{ peticion.competicion.nombre }}" fue aprobada.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% elseif peticion.status.value == 'REJECTED' %}
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                Tu solicitud sobre "{{ peticion.competicion.nombre }}" fue rechazada.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>

        {% endif %}
    </div>

{% endif %}

<script>
    window.addEventListener('DOMContentLoaded', () => {
        const toastEl = document.querySelector('.toast');
        if (toastEl) {
            const toast = new bootstrap.Toast(toastEl);
            toast.show();
        }
    });
</script>

templates/forms/equipoEdit.html.twig
<div class="modal fade" id="modalEditarEquipo" tabindex="-1" aria-labelledby="modalEditarEquipoLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="titulomodalEditarEquipo">Editar Equipo</h5>
                <button type="button" class="btn-close cerrar-modal-equipo" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>

            <div class="modal-body">
                <div class="alert alert-success d-none" id="alerta-modal-editar" role="alert">
                    Equipo actualizado correctamente.
                </div>
                <form id="formEditarEquipo" method="post">
                    <input type="hidden" id="equipo-id" name="equipo-id">

                    <div class="mb-3">
                        <label for="nombre-equipo" class="form-label">Nombre del Equipo</label>
                        <input type="text" name="nombre-equipo" class="form-control" id="nombre-equipo" required>
                        <label for="nombre-entrenador" class="form-label">Nombre del Entrenador</label>
                        <input type="text" name="nombre-entrenador" class="form-control" id="nombre-entrenador" required>
                        <label for="competicion-id" class="form-label">Competicion</label>
                        <select name="competicion-id" id="competicion-id"class="form-control" required>
                            <option value="">Seleccione una competicion</option>
                            {% for competicion in competiciones %}
                                <option value="{{ competicion.id }}">{{ competicion.nombre }} - {{ competicion.admin.username }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <button type="submit" class="btn btn-success">Guardar</button>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary cerrar-modal-equipo" data-bs-dismiss="modal">Cerrar</button>
            </div>

        </div>
    </div>
</div>

<script>
    $('#formEditarEquipo').submit(function (e) {
        e.preventDefault();

        const id = $('#equipo-id').val();
        const datos = {
            nombreEquipo: $('#nombre-equipo').val(),
            nombreEntrenador: $('#nombre-entrenador').val(),
            competicionId: $('#competicion-id').val()
        };

        $.ajax({
            url: `/admin/equipo/${id}/edit`,
            type: 'PUT',
            data: datos,
            success: function () {
                const alerta = $('#alerta-modal-editar');
                alerta.removeClass('d-none');
            },
            error: function () {
                alert('Error al editar el equipo.');
            }
        });
    });

    $('.cerrar-modal-equipo').on('click', function () {
        $('#btn-equipos').trigger('click');
        $('#alerta-modal-editar').addClass('d-none');
    });

</script>

templates/forms/equipoNuevo.html.twig
<div class="modal fade" id="modalCrearEquipo" tabindex="-1" aria-labelledby="modalCrearEquipo" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="titulomodalCrearEquipo">Crear Equipo</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>

            <div class="modal-body">
                <form id="formCrearEquipo" action="{{ path('crear_equipo') }}" method="post">

                    <div class="mb-3">
                        <label for="nombreEquipo" class="form-label">Nombre del Equipo</label>
                        <input type="text" name="nombreEquipo" class="form-control" id="nombreEquipo" required>
                        <label for="nombreEntrenador" class="form-label">Nombre del Entrenador</label>
                        <input type="text" name="nombreEntrenador" class="form-control" id="nombreEntrenador" required>
                        <label for="competicion" class="form-label">Competicion</label>
                        <select name="competicion" id="competicion"class="form-control" required>
                            <option value="">Seleccione una competicion</option>
                            {% for competicion in competiciones %}
                                <option value="{{ competicion.id }}">{{ competicion.nombre }} - {{ competicion.admin.username }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <button type="submit" class="btn btn-success">Guardar</button>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>

        </div>
    </div>
</div>

templates/forms/jugadorEdit.html.twig
<div class="modal fade" id="modalEditarJugador" tabindex="-1" aria-labelledby="modalEditarJugadorLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="titulomodalEditarJugador">Editar Jugador</h5>
                <button type="button" class="btn-close cerrar-modal-jugador" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>

            <div class="modal-body">
                <div class="alert alert-success d-none" id="alerta-modal-editar" role="alert">
                    Jugador actualizado correctamente.
                </div>
                <form id="formEditarJugador" method="post">
                    <input type="hidden" id="jugador-id" name="jugador-id">

                    <div class="mb-3">
                        <label for="nombre-jugador" class="form-label">Nombre del Jugador</label>
                        <input type="text" name="nombre-jugador" class="form-control" id="nombre-jugador" required>
                        <label for="nombre-equipo" class="form-label" >Selecciona su Equipo</label>
                        <select name="nombre-equipo" id="nombre-equipo"class="form-control" required>
                            <option value="">Seleccione un equipo</option>
                            {% for equipo in equipos %}
                                <option value="{{ equipo.id }}">{{ equipo.nombre }}</option>
                            {% endfor %}
                        </select>
                        <label for="posicion" class="form-label">Posicion</label>
                        <select name="posicion" id="posicion-id" class="form-control">
                            <option value="Base">Base</option>
                            <option value="Escolta">Escolta</option>
                            <option value="Alero">Alero</option>
                            <option value="Ala-Pivot">Ala-Pívot</option>
                            <option value="Pivot">Pívot</option>
                        </select>
                        <label for="altura" class="form-label">Altura</label>
                        <input type="number" name="altura" id="altura-id" min="1" step="0.01" class="form-control">
                        <label for="dorsal" class="form-label">Dorsal</label>
                        <input type="number" name="dorsal" id="dorsal-id" min="0" max="99" class="form-control">
                    </div>

                    <button type="submit" class="btn btn-success">Guardar</button>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary cerrar-modal-jugador" data-bs-dismiss="modal">Cerrar</button>
            </div>

        </div>
    </div>
</div>

<script>
    $('#formEditarJugador').submit(function (e) {
        e.preventDefault();

        const id = $('#jugador-id').val();
        const datos = {
            nombreJugador: $('#nombre-jugador').val(),
            idEquipo: $('#nombre-equipo').val(),
            posicion: $('#posicion-id').val(),
            altura: $('#altura-id').val(),
            dorsal: $('#dorsal-id').val(),
        };

        $.ajax({
            url: `/admin/jugador/${id}/edit`,
            type: 'PUT',
            data: datos,
            success: function () {
                const alerta = $('#alerta-modal-editar');
                alerta.removeClass('d-none');
            },
            error: function () {
                alert('Error al editar el jugador.');
            }
        });
    });

    $('.cerrar-modal-jugador').on('click', function () {
        $('#btn-jugadores').trigger('click');
        $('#alerta-modal-editar').addClass('d-none');
    });

</script>

templates/forms/jugadorNuevo.html.twig
<div class="modal fade" id="modalCrearJugador" tabindex="-1" aria-labelledby="modalCrearJugador" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="titulomodalCrearJugador">Crear Jugador</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>

            <div class="modal-body">
                <form id="formCrearJugador" action="{{ path('crear_jugador') }}" method="post">

                    <div class="mb-3">
                        <label for="nombreJugador" class="form-label">Nombre del Jugador</label>
                        <input type="text" name="nombreJugador" class="form-control" id="nombreJugador" required>
                        <label for="nombreEquipo" class="form-label" >Selecciona su Equipo</label>
                        <select name="nombreEquipo" id="nombreEquipo"class="form-control" required>
                            <option value="">Seleccione un equipo</option>
                            {% for equipo in equipos %}
                                <option value="{{ equipo.id }}">{{ equipo.nombre }}</option>
                            {% endfor %}
                        </select>
                        <label for="posicion" class="form-label">Posicion</label>
                        <select name="posicion" id="posicion" class="form-control" required>
                            <option value="Base">Base</option>
                            <option value="Escolta">Escolta</option>
                            <option value="Alero">Alero</option>
                            <option value="Ala-pivot">Ala-Pivot</option>
                            <option value="Pivot">Pivot</option>
                        </select>
                        <label for="altura" class="form-label">Altura</label>
                        <input type="number" name="altura" id="altura" min="1" step="0.01" class="form-control">
                        <label for="dorsal" class="form-label">Dorsal</label>
                        <input type="number" name="dorsal" id="dorsal" min="0" max="99" class="form-control" required>


                    </div>

                    <button type="submit" class="btn btn-success">Guardar</button>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>

        </div>
    </div>
</div>